metadata:
  version: "0.1.0"
  last_updated: "2025-01-18"
  author: "Keisuke ANDO"

# File type definitions
file_types:
  main_data:
    encoding: "Shift_JIS"
    delimiter: ","
    pattern: "honhyo[_][0-9]{4}[.]csv"
    columns:
      - "資料区分"
      - "都道府県コード"
      - "警察署等コード"
      - "本票番号"
      - "事故内容"
      - "死者数"
      - "負傷者数"
      - "路線コード"
      - "上下線"
      - "地点コード"
      - "市区町村コード"
      - "発生日時　　年"
      - "発生日時　　月"
      - "発生日時　　日"
      - "発生日時　　時"
      - "発生日時　　分"
      - "昼夜"
      - "日の出時刻　　時"
      - "日の出時刻　　分"
      - "日の入り時刻　　時"
      - "日の入り時刻　　分"
      - "天候"
      - "環状交差点の直径"
      - "地形"
      - "路面状態"
      - "道路形状"
      - "信号機"
      - "一時停止規制　標識（当事者A）"
      - "一時停止規制　表示（当事者A）"
      - "一時停止規制　標識（当事者B）"
      - "一時停止規制　表示（当事者B）"
      - "車道幅員"
      - "道路線形"
      - "衝突地点"
      - "ゾーン規制"
      - "中央分離帯施設等"
      - "歩車道区分"
      - "事故類型"
      - "年齢（当事者A）"
      - "年齢（当事者B）"
      - "当事者種別（当事者A）"
      - "当事者種別（当事者B）"
      - "用途別（当事者A）"
      - "用途別（当事者B）"
      - "車両形状（当事者A）"
      - "車両形状等（当事者A）"
      - "車両形状（当事者B）"
      - "車両形状等（当事者B）"
      - "オートマチック車（当事者A）"
      - "オートマチック車（当事者B）"
      - "サポカー（当事者A）"
      - "サポカー（当事者B）"
      - "速度規制（指定のみ）（当事者A）"
      - "速度規制（指定のみ）（当事者B）"
      - "車両の衝突部位（当事者A）"
      - "車両の衝突部位（当事者B）"
      - "車両の損壊程度（当事者A）"
      - "車両の損壊程度（当事者B）"
      - "エアバッグの装備（当事者A）"
      - "エアバッグの装備（当事者B）"
      - "サイドエアバッグの装備（当事者A）"
      - "サイドエアバッグの装備（当事者B）"
      - "人身損傷程度（当事者A）"
      - "人身損傷程度（当事者B）"
      - "地点　緯度（北緯）"
      - "地点　経度（東経）"
      - "曜日(発生年月日)"
      - "祝日(発生年月日)"
      - "認知機能検査経過日数（当事者A）"
      - "認知機能検査経過日数（当事者B）"
      - "運転練習の方法（当事者A）"
      - "運転練習の方法（当事者B）"
  sub_data:
    encoding: "Shift_JIS"
    delimiter: ","
    pattern: "hojuhyo[_][0-9]{4}[.]csv"
    columns:
      - "資料区分"
      - "都道府県コード"
      - "警察署等コード"
      - "本票番号"
      - "補充票番号"
      - "当事者種別"
      - "用途別"
      - "車両形状等"
      - "乗車別"
      - "乗車等の区分"
      - "サポカー"
      - "エアバッグの装備"
      - "サイドエアバッグの装備"
      - "人身損傷程度"
      - "車両の衝突部位"
      - "車両の損壊程度"
  highway_data:
    encoding: "Shift_JIS"
    delimiter: ","
    pattern: "kosokuhyo[_][0-9]{4}[.]csv"
    columns:
      - "資料区分"
      - "都道府県コード"
      - "警察署等コード"
      - "本票番号"
      - "発生地点"
      - "道路管理者区分"
      - "道路区分"
      - "曲線半径"
      - "縦断勾配"
      - "トンネル番号"
      - "当事者車両台数"
      - "事故類型"
      - "車両単独事故の対象物"
      - "臨時速度規制の有無"
      - "速度規制（臨時のみ）"
      - "トンネル延長距離"

# Logical schema definitions
schemas:
  accident_info:
    primary_key:
      - document_type
      - prefecture_code
      - police_code
      - main_id
    data_columns:
      - injury_pattern
      - faitality_number
      - injury_number
      - road_code
      - road_direction
      - kilopost_number
      - city_code
      - occurrence_time
      - day_night
      - sunrise_hour
      - sunrise_min
      - sunset_hour
      - sunset_min
      - weather
      - roundabout_diameter
      - region_type
      - road_surface
      - road_shape
      - traffic_signal
      - road_width
      - road_alignment
      - collision_position
      - zone_regulation
      - center_divider
      - road_verge
      - impact_type
      - day_of_week
      - holiday
      - geometry
    source_files:
      - main_data
  person_info:
    primary_key:
      - document_type
      - prefecture_code
      - police_code
      - main_id
      - sub_id
    data_columns:
      - stop_sign
      - stop_mark
      - age
      - party_type
      - use_type
      - car_type
      - automatic_car
      - support_car
      - speed_limit
      - impact_part
      - damage_level
      - airbag
      - side_airbag
      - injury_level
      - cognitive_test
      - driving_practice
    source_files:
      - main_data
      - sub_data
  highway_info:
    primary_key:
      - document_type
      - prefecture_code
      - police_code
      - main_id
    data_columns:
      - kilopost_number
      - road_manager
      - highway_type
      - curve_radius
      - longitudinal_slope
      - tunnel_number
      - car_count
      - impact_type
      - damaged_property
      - limit_type
      - temp_limit
      - tunnel_length
    source_files:
      - highway_data

# Column name variations mapping
columns:
    document_type:
      - "資料区分"
    prefecture_code:
      - "都道府県コード"
    police_code:
      - "警察署等コード"
    main_id:
      - "本票番号"
    injury_pattern:
      - "事故内容"
    faitality_number:
      - "死者数"
    injury_number:
      - "負傷者数"
    road_code:
      - "路線コード"
    road_direction:
      - "上下線"
    kilopost_number:
      - "地点コード"
      - "発生地点"
    city_code:
      - "市区町村コード"
    occurrence_year:
      - "発生日時　　年"
    occurrence_month:
      - "発生日時　　月"
    occurrence_day:
      - "発生日時　　日"
    occurrence_hour:
      - "発生日時　　時"
    occurrence_min:
      - "発生日時　　分"
    day_night:
      - "昼夜"
    sunrise_hour:
      - "日の出時刻　　時"
    sunrise_min:
      - "日の出時刻　　分"
    sunset_hour:
      - "日の入り時刻　　時"
    sunset_min:
      - "日の入り時刻　　分"
    weather:
      - "天候"
    roundabout_diameter:
      - "環状交差点の直径"
    region_type:
      - "地形"
    road_surface:
      - "路面状態"
    road_shape:
      - "道路形状"
    traffic_signal:
      - "信号機"
    stop_sign_a:
      - "一時停止規制　標識（当事者A）"
    stop_mark_a:
      - "一時停止規制　表示（当事者A）"
    stop_sign_b:
      - "一時停止規制　標識（当事者B）"
    stop_mark_b:
      - "一時停止規制　表示（当事者B）"
    road_width:
      - "車道幅員"
    road_alignment:
      - "道路線形"
    collision_position:
      - "衝突地点"
    zone_regulation:
      - "ゾーン規制"
    center_divider:
      - "中央分離帯施設等"
    road_verge:
      - "歩車道区分"
    impact_type:
      - "事故類型"
    age_a:
      - "年齢（当事者A）"
    age_b:
      - "年齢（当事者B）"
    party_type_a:
      - "当事者種別（当事者A）"
    party_type_b:
      - "当事者種別（当事者B）"
    use_type_a:
      - "用途別（当事者A）"
    use_type_b:
      - "用途別（当事者B）"
    car_type_a:
      - "車両形状（当事者A）"
      - "車両形状等（当事者A）"
    car_type_b:
      - "車両形状（当事者B）"
      - "車両形状等（当事者B）"
    automatic_car_a:
      - "オートマチック車（当事者A）"
    automatic_car_b:
      - "オートマチック車（当事者B）"
    support_car_a:
      - "サポカー（当事者A）"
    support_car_b:
      - "サポカー（当事者B）"
    speed_limit_a:
      - "速度規制（指定のみ）（当事者A）"
    speed_limit_b:
      - "速度規制（指定のみ）（当事者B）"
    impact_part_a:
      - "車両の衝突部位（当事者A）"
    impact_part_b:
      - "車両の衝突部位（当事者B）"
    damage_level_a:
      - "車両の損壊程度（当事者A）"
    damage_level_b:
      - "車両の損壊程度（当事者B）"
    airbag_a:
      - "エアバッグの装備（当事者A）"
    airbag_b:
      - "エアバッグの装備（当事者B）"
    side_airbag_a:
      - "サイドエアバッグの装備（当事者A）"
    side_airbag_b:
      - "サイドエアバッグの装備（当事者B）"
    injury_level_a:
      - "人身損傷程度（当事者A）"
    injury_level_b:
      - "人身損傷程度（当事者B）"
    latitude:
      - "地点　緯度（北緯）"
    longitude:
      - "地点　経度（東経）"
    day_of_week:
      - "曜日(発生年月日)"
    holiday:
      - "祝日(発生年月日)"
    cognitive_test_a:
      - "認知機能検査経過日数（当事者A）"
    cognitive_test_b:
      - "認知機能検査経過日数（当事者B）"
    driving_practice_a:
      - "運転練習の方法（当事者A）"
    driving_practice_b:
      - "運転練習の方法（当事者B）"
    sub_id:
      - "補充票番号"
    party_type:
      - "当事者種別"
    use_type:
      - "用途別"
    car_type:
      - "車両形状等"
    boarding_type:
      - "乗車別"
    boarding_tag:
      - "乗車等の区分"
    support_car:
      - "サポカー"
    airbag:
      - "エアバッグの装備"
    side_airbag:
      - "サイドエアバッグの装備"
    injury_level:
      - "人身損傷程度"
    impact_part:
      - "車両の衝突部位"
    damage_level:
      - "車両の損壊程度"
    road_manager:
      - "道路管理者区分"
    highway_type:
      - "道路区分"
    curve_radius:
      - "曲線半径"
    longitudinal_slope:
      - "縦断勾配"
    tunnel_number:
      - "トンネル番号"
    car_count:
      - "当事者車両台数"
    damaged_property:
      - "車両単独事故の対象物"
    limit_type:
      - "臨時速度規制の有無"
    temp_limit:
      - "速度規制（臨時のみ）"
    tunnel_length:
      - "トンネル延長距離"

# Code mapping
concepts:
  document_type:
    main:
      codes: "1"
      names:
        en: "main"
        jp: "本票"
    sub:
      codes: "2"
      names:
        en: "sub"
        jp: "補充票"
    highway:
      codes: "3"
      names:
        en: "highway"
        jp: "高速票"

  impact_part:
    front:
      codes: "1"
      names:
        en: "front"
        jp: "前方"
    right:
      codes: "2"
      names:
        en: "right"
        jp: "右方"
    rear:
      codes: "3"
      names:
        en: "rear"
        jp: "後方"
    left:
      codes: "4"
      names:
        en: "left"
        jp: "左方"
    front_right:
      codes: "5"
      names:
        en: "front_right"
        jp: "前方右"
    rear_right:
      codes: "6"
      names:
        en: "rear_right"
        jp: "後方右"
    rear_left:
      codes: "7"
      names:
        en: "rear_left"
        jp: "後方左"
    front_left:
      codes: "8"
      names:
        en: "front_left"
        jp: "前方左"
