main_data:
  file_pattern: "honhyo[_][0-9]{4}[.]csv"
  columns:
    document_type:
      original_name: "資料区分"
      tag: "key"
    prefecture_code:
      original_name: "都道府県コード"
      tag: "key"
    police_code:
      original_name: "警察署等コード"
      tag: "key"
    main_id:
      original_name: "本票番号"
      tag: "key"
    injury_pattern:
      original_name: "事故内容"
      tag: "accident"
    faitality_number:
      original_name: "死者数"
      tag: "accident"
    injury_number:
      original_name: "負傷者数"
      tag: "accident"
    road_code:
      original_name: "路線コード"
      tag: "accident"
    road_direction:
      original_name: "上下線"
      tag: "accident"
    kilopost_number:
      original_name: "地点コード"
      tag: "accident"
    city_code:
      original_name: "市区町村コード"
      tag: "accident"
    occurrence_year:
      original_name: "発生日時　　年"
    occurrence_month:
      original_name: "発生日時　　月"
    occurrence_day:
      original_name: "発生日時　　日"
    occurrence_hour:
      original_name: "発生日時　　時"
    occurrence_min:
      original_name: "発生日時　　分"
    day_night:
      original_name: "昼夜"
      tag: "accident"
    sunrise_hour:
      original_name: "日の出時刻　　時"
      tag: "accident"
    sunrise_min:
      original_name: "日の出時刻　　分"
      tag: "accident"
    sunset_hour:
      original_name: "日の入り時刻　　時"
      tag: "accident"
    sunset_min:
      original_name: "日の入り時刻　　分"
      tag: "accident"
    weather:
      original_name: "天候"
      tag: "accident"
    roundabout_diameter:
      original_name: "環状交差点の直径"
      tag: "accident"
    region_type:
      original_name: "地形"
      tag: "accident"
    road_surface:
      original_name: "路面状態"
      tag: "accident"
    road_shape:
      original_name: "道路形状"
      tag: "accident"
    traffic_signal:
      original_name: "信号機"
      tag: "accident"
    stop_sign_a:
      original_name: "一時停止規制　標識（当事者A）"
      tag: "person_a"
    stop_mark_a:
      original_name: "一時停止規制　表示（当事者A）"
      tag: "person_a"
    stop_sign_b:
      original_name: "一時停止規制　標識（当事者B）"
      tag: "person_b"
    stop_mark_b:
      original_name: "一時停止規制　表示（当事者B）"
      tag: "person_b"
    road_width:
      original_name: "車道幅員"
      tag: "accident"
    road_alignment:
      original_name: "道路線形"
      tag: "accident"
    collision_position:
      original_name: "衝突地点"
      tag: "accident"
    zone_regulation:
      original_name: "ゾーン規制"
      tag: "accident"
    center_divider:
      original_name: "中央分離帯施設等"
      tag: "accident"
    road_verge:
      original_name: "歩車道区分"
      tag: "accident"
    impact_type:
      original_name: "事故類型"
      tag: "accident"
    age_a:
      original_name: "年齢（当事者A）"
      tag: "person_a"
    age_b:
      original_name: "年齢（当事者B）"
      tag: "person_b"
    party_type_a:
      original_name: "当事者種別（当事者A）"
      tag: "person_a"
    party_type_b:
      original_name: "当事者種別（当事者B）"
      tag: "person_b"
    use_type_a:
      original_name: "用途別（当事者A）"
      tag: "person_a"
    use_type_b:
      original_name: "用途別（当事者B）"
      tag: "person_b"
    car_type_a:
      original_name:
        - "車両形状（当事者A）"
        - "車両形状等（当事者A）"
      tag: "person_a"
    car_type_b:
      original_name:
        - "車両形状（当事者B）"
        - "車両形状等（当事者B）"
      tag: "person_b"
    automatic_car_a:
      original_name: "オートマチック車（当事者A）"
      tag: "person_a"
    automatic_car_b:
      original_name: "オートマチック車（当事者B）"
      tag: "person_b"
    support_car_a:
      original_name: "サポカー（当事者A）"
      tag: "person_a"
    support_car_b:
      original_name: "サポカー（当事者B）"
      tag: "person_b"
    speed_limit_a:
      original_name: "速度規制（指定のみ）（当事者A）"
      tag: "person_a"
    speed_limit_b:
      original_name: "速度規制（指定のみ）（当事者B）"
      tag: "person_b"
    impact_part_a:
      original_name: "車両の衝突部位（当事者A）"
      tag: "person_a"
    impact_part_b:
      original_name: "車両の衝突部位（当事者B）"
      tag: "person_b"
    damage_level_a:
      original_name: "車両の損壊程度（当事者A）"
      tag: "person_a"
    damage_level_b:
      original_name: "車両の損壊程度（当事者B）"
      tag: "person_b"
    airbag_a:
      original_name: "エアバッグの装備（当事者A）"
      tag: "person_a"
    airbag_b:
      original_name: "エアバッグの装備（当事者B）"
      tag: "person_b"
    side_airbag_a:
      original_name: "サイドエアバッグの装備（当事者A）"
      tag: "person_a"
    side_airbag_b:
      original_name: "サイドエアバッグの装備（当事者B）"
      tag: "person_b"
    injury_level_a:
      original_name: "人身損傷程度（当事者A）"
      tag: "person_a"
    injury_level_b:
      original_name: "人身損傷程度（当事者B）"
      tag: "person_b"
    latitude:
      original_name: "地点　緯度（北緯）"
      tag: "accident"
    longitude:
      original_name: "地点　経度（東経）"
      tag: "accident"
    day_of_week:
      original_name: "曜日(発生年月日)"
      tag: "accident"
    holiday:
      original_name: "祝日(発生年月日)"
      tag: "accident"
    cognitive_test_a:
      original_name: "認知機能検査経過日数（当事者A）"
      tag: "person_a"
    cognitive_test_b:
      original_name: "認知機能検査経過日数（当事者B）"
      tag: "person_b"
    driving_practice_a:
      original_name: "運転練習の方法（当事者A）"
      tag: "person_a"
    driving_practice_b:
      original_name: "運転練習の方法（当事者B）"
      tag: "person_b"

sub_data:
  file_pattern: "hojuhyo[_][0-9]{4}[.]csv"
  columns:
    document_type:
      original_name: "資料区分"
    prefecture_code:
      original_name: "都道府県コード"
    police_code:
      original_name: "警察署等コード"
    main_id:
      original_name: "本票番号"
    sub_id:
      original_name: "補充票番号"
    party_type:
      original_name: "当事者種別"
    use_type:
      original_name: "用途別"
    car_type:
      original_name: "車両形状等"
    boarding_type:
      original_name: "乗車別"
    boarding_tag:
      original_name: "乗車等の区分"
    support_car:
      original_name: "サポカー"
    airbag:
      original_name: "エアバッグの装備"
    side_airbag:
      original_name: "サイドエアバッグの装備"
    injury_level:
      original_name: "人身損傷程度"
    impact_part:
      original_name: "車両の衝突部位"
    damage_level:
      original_name: "車両の損壊程度"

highway_data:
  file_pattern: "kosokuhyo[_][0-9]{4}[.]csv"
  columns:
    document_type:
      original_name: "資料区分"
    prefecture_code:
      original_name: "都道府県コード"
    police_code:
      original_name: "警察署等コード"
    main_id:
      original_name: "本票番号"
    kilopost_number:
      original_name: "発生地点"
    road_manager:
      original_name: "道路管理者区分"
    highway_type:
      original_name: "道路区分"
    curve_radius:
      original_name: "曲線半径"
    longitudinal_slope:
      original_name: "縦断勾配"
    tunnel_number:
      original_name: "トンネル番号"
    car_count:
      original_name: "当事者車両台数"
    impact_type:
      original_name: "事故類型"
    damaged_property:
      original_name: "車両単独事故の対象物"
    limit_type:
      original_name: "臨時速度規制の有無"
    temp_limit:
      original_name: "速度規制（臨時のみ）"
    tunnel_length:
      original_name: "トンネル延長距離"
